<?php

namespace Tests\Feature;

use Tests\TestCase;
use Illuminate\Foundation\Testing\WithFaker;
use Illuminate\Foundation\Testing\RefreshDatabase;

class RoleTest extends TestCase
{
  use RefreshDatabase ;

  protected $user;

  public function setUp()
  {
      parent::setUp(); // TODO: Change the autogenerated stub
      $this->user  = factory('App\User')->create();
      $role = factory('App\Role')->create(['name' => 'Admin']);
      $this->user->assignRoles($role->id);
      $this->actingAs($this->user);
  }


  /** @test **/

  public function admin_can_inactivate_the_role()
  {
    $testRole = factory('App\Role')->create();
    $this->put('role/'.$testRole->id);
    $this->assertDatabaseHas('roles',['id'=> $testRole->id , 'active'=> 0]);
  }

  /** @test **/

  public function admin_can_activate_the_role()
  {
    $testRole = factory('App\Role')->create(['active' => 0]);
    $this->put('role/'.$testRole->id,['active'=>'on']);
    $this->assertDatabaseHas('roles',['id'=> $testRole->id , 'active'=> 1]);
  }
  
}
